[tool.poetry]
name = "vss365today"
version = "1.0.0"
description = "#vss365 today website"
authors = ["Caleb <le717@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^2.0.1"
flask-wtf = "^0.15.1"
gunicorn = "^20.0.4"
requests = "^2.25.1"
email-validator = "^1.1.3"
WTForms-Components = "^0.10.4"
sys-vars = "^4.0.0"
num2words = "^0.5.10"

[tool.poetry.dev-dependencies]
flake8 = "^3.9.2"
mypy = "^0.910"
black = "^21.6b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
